// Define perfumesData globally
var perfumesData = [
  {"Id":1,"Name":"B@re-Vanilla","Brand":"Victoria's Secret","Category":"Gourmand","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BARE VANILLA.png"},
  {"Id":2,"Name":"Scandal","Brand":"Jean Paul Gaultier","Category":"Honey/Floral","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SCANDAL.png"},
  {"Id":3,"Name":"Tasteful Cherries","Brand":"La Petite Robe Noire","Category":"Fruity/Floral","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/TASTSEFUL CHERRIES.png"},
  {"Id":4,"Name":"Vanilla Power","Brand":"Generic","Category":"Gourmand","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/VANILLA POWDER.png"},
  {"Id":5,"Name":"BBW Gingham","Brand":"Bath & Body Works","Category":"Fresh/Floral","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/GINGHAM.png"},
  {"Id":6,"Name":"Velvet Petals","Brand":"Victoria's Secret","Category":"Floral/Sweet","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/VELVET PETALS.png"},
  {"Id":7,"Name":"Sweet Like Candy","Brand":"Ariana Grande","Category":"Sweet/Gourmand","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SWEET LIKE CANDY.png"},
  {"Id":8,"Name":"Salted Pistacio","Brand":"Generic","Category":"Gourmand","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SALTED PISTACHIO.png"},
  {"Id":9,"Name":"V.s Velvet Petals","Brand":"Victoria's Secret","Category":"Floral/Sweet","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/VELVET PETALS.png"},
  {"Id":10,"Name":"L-cost PINK","Brand":"Lacoste","Category":"Floral/Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LACOSTE PINK.png"},
  {"Id":11,"Name":"BBW Japanese Cherry","Brand":"Bath & Body Works","Category":"Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/JAPANESSE CHERRY.png"},
  {"Id":12,"Name":"Chann No.5","Brand":"Chanel","Category":"Floral/Aldehydic","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/N°5.png"},
  {"Id":13,"Name":"Women Issey","Brand":"Issey Miyake","Category":"Aquatic/Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/WOMEN ISSEY.png"},
  {"Id":14,"Name":"Mango Flower","Brand":"Generic","Category":"Fruity/Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/scnt_default.png"},
  {"Id":15,"Name":"Golden Vanilla","Brand":"Generic","Category":"Gourmand","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/GOLDEN VANILLA.png"},
  {"Id":16,"Name":"B@byPowder Lavander","Brand":"Generic","Category":"Floral/Powdery","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BABY POWDER LAVENDER.png"},
  {"Id":17,"Name":"BabyPowder Pink","Brand":"Generic","Category":"Powdery","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BABY POWDER PINK.png"},
  {"Id":18,"Name":"BabyPowder Classic","Brand":"Generic","Category":"Powdery/Clean","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BABY POWDER CLASSIC.png"},
  {"Id":19,"Name":"BBW Dark Kiss","Brand":"Bath & Body Works","Category":"Berry/Musk","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/DARK KISS.png"},
  {"Id":20,"Name":"BBW Pink Chiffon","Brand":"Bath & Body Works","Category":"Sweet/Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/PINK CHIFFON.png"},
  {"Id":21,"Name":"BBW Sweet Pea","Brand":"Bath & Body Works","Category":"Floral/Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SWEET PEA.png"},
  {"Id":22,"Name":"BBW Warm Vanilla","Brand":"Bath & Body Works","Category":"Gourmand","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/WARM VANILLA.png"},
  {"Id":23,"Name":"Br.Spear FANTASY","Brand":"Britney Spears","Category":"Sweet/Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/FANSTASY.png"},
  {"Id":24,"Name":"Bright Purple Gem","Brand":"Generic","Category":"Floral/Berry","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BRIGHT PURPLE GEM.png"},
  {"Id":25,"Name":"Bur. Weekend","Brand":"Burberry","Category":"Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/WEEKEND.png"},
  {"Id":26,"Name":"Ch0c0 Vanilla","Brand":"Generic","Category":"Gourmand","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/CHOCO VANILLA.png"},
  {"Id":27,"Name":"Cloud v2","Brand":"Ariana Grande","Category":"Sweet/Musk","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/CLOUD v2.png"},
  {"Id":28,"Name":"CooL Women","Brand":"Davidoff","Category":"Fresh/Aquatic","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/COOL WOMEN.png"},
  {"Id":29,"Name":"EC3CLAT","Brand":"Lanvin","Category":"Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/ECLAT.png"},
  {"Id":30,"Name":"Girly Charm","Brand":"Generic","Category":"Floral/Sweet","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/GIRLY CHARM.png"},
  {"Id":31,"Name":"Good Girl","Brand":"Carolina Herrera","Category":"Amber/Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/scnt_default.png"},
  {"Id":32,"Name":"I Stan You","Brand":"Generic","Category":"Floral/Sweet","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/I STAN YOU.png"},
  {"Id":33,"Name":"I.love.Matcha","Brand":"Generic","Category":"Green/Fresh","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/I LOVE MATCHA.png"},
  {"Id":34,"Name":"Ibiza","Brand":"Generic","Category":"Tropical/Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/IBIZA.png"},
  {"Id":35,"Name":"J.M English&Pear","Brand":"Jo Malone","Category":"Fruity/Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/ENGLISH PEAR.png"},
  {"Id":36,"Name":"JoMa Nectarine Blosm","Brand":"Jo Malone","Category":"Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/NECTARINE BLOSM.png"},
  {"Id":37,"Name":"JoMa Peony&Blush","Brand":"Jo Malone","Category":"Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/PEONY AND BLUSH.png"},
  {"Id":38,"Name":"Jovan Women","Brand":"Jovan","Category":"Musk/Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/JOVAN.png"},
  {"Id":39,"Name":"Katty Meow 2","Brand":"Katy Perry","Category":"Sweet","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/MEOW v2.png"},
  {"Id":40,"Name":"King Blue","Brand":"Generic","Category":"Fresh/Aquatic","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/KING BLUE.png"},
  {"Id":41,"Name":"L Touch of Pink","Brand":"Lacoste","Category":"Floral/Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/TOUCH OF PINK.png"},
  {"Id":42,"Name":"Light Blue Women","Brand":"D&G","Category":"Citrus/Fresh","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LIGHT BLUE WOMEN.png"},
  {"Id":43,"Name":"SO in love","Brand":"Victoria's Secret","Category":"Floral","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SO IN LOVE.png"},
  {"Id":44,"Name":"Sweet Melon","Brand":"Generic","Category":"Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SWEET MELON.png"},
  {"Id":45,"Name":"Sylena Gomez","Brand":"Selena Gomez","Category":"Floral/Sweet","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SELENA GOMEZ.png"},
  {"Id":46,"Name":"Vanilla Goddess","Brand":"Generic","Category":"Gourmand","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/VANILLA GODDESS.png"},
  {"Id":47,"Name":"VS Amber Romance","Brand":"Victoria's Secret","Category":"Amber/Sweet","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/AMBER ROMANCE.png"},
  {"Id":48,"Name":"VS Romantic Wish","Brand":"Victoria's Secret","Category":"Floral/Fruity","Size":"85ml, ","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/ROMANTIC WISH.png"},
  {"Id":49,"Name":"BBW Cucumber Melon","Brand":"Bath & Body Works","Category":"Fresh/Fruity","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/CUCUMBER MELON.png"},
  {"Id":50,"Name":"CLOUD @riana.","Brand":"Ariana Grande","Category":"Sweet/Musk","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/CLOUD.png"}
,
  {"Id":51,"Name":"Incanto SHINE","Brand":"Ferragamo","Category":"Fruity/Floral","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/INCANTO SHINE.png"},
  {"Id":52,"Name":"Katty MEOW","Brand":"Katy Perry","Category":"Sweet","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/MEOW.png"},
  {"Id":53,"Name":"Omn. Amety","Brand":"Bvlgari","Category":"Floral/Powdery","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/OMNIA AMETHYSTE.png"},
  {"Id":54,"Name":"V.s Bomb-shell","Brand":"Victoria's Secret","Category":"Fruity/Floral","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BOMBSHELL.png"},
  {"Id":55,"Name":"V.S Love-Spell","Brand":"Victoria's Secret","Category":"Fruity/Floral","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LOVE SPELL.png"},
  {"Id":56,"Name":"V.S PURE SEDUC","Brand":"Victoria's Secret","Category":"Fruity","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/PURE SEDUCTION.png"},
  {"Id":57,"Name":"V.s Vanilla lace","Brand":"Victoria's Secret","Category":"Gourmand","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/VANILLA LACE.png"},
  {"Id":58,"Name":"Valaya Lumiere","Brand":"Parfums de Marly","Category":"Floral/Fresh","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/VANILLA LUMIERE.png"},
  {"Id":59,"Name":"Bare Vanilla","Brand":"Victoria's Secret","Category":"Gourmand","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BARE VANILLA.png"},
  {"Id":60,"Name":"Dyore Sauvage","Brand":"Dior","Category":"Fresh/Spicy","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SAUVAGE DIOR.png"},
  {"Id":61,"Name":"Ferrari. Black","Brand":"Ferrari","Category":"Aromatic","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/FERRARI BLACK.png"},
  {"Id":62,"Name":"Baccarat Germany","Brand":"MFK","Category":"Amber/Woody","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/BACCARAT.png"},
  {"Id":63,"Name":"Eros Desire","Brand":"Versace","Category":"Aromatic/Spicy","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/EROS DESIRE.png"},
  {"Id":64,"Name":"Aventus","Brand":"Creed","Category":"Fruity/Woody","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/CREED.png"},
  {"Id":65,"Name":"1MILLION","Brand":"Paco Rabanne","Category":"Spicy/Woody","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/1 MILLION.png"},
  {"Id":66,"Name":"Polo Blue","Brand":"Ralph Lauren","Category":"Fresh/Aquatic","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/POLO BLUE.png"},
  {"Id":67,"Name":"Lcost BLACK","Brand":"Lacoste","Category":"Aromatic","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LACOSTE BLACK.png"},
  {"Id":68,"Name":"Drakkar","Brand":"Guy Laroche","Category":"Aromatic/Woody","Size":"85ml, ","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/DRAKKAR NOIR.png"},
  {"Id":69,"Name":"Invictuss","Brand":"Paco Rabanne","Category":"Fresh/Aquatic","Size":"85ml, ","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/INVICTUSS.png"},
  {"Id":70,"Name":"Savage La Perfume","Brand":"Dior","Category":"Spicy/Amber","Size":"85ml, ","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SAUVAGE.png"},
  {"Id":71,"Name":"L-White 12.12","Brand":"Lacoste","Category":"Fresh/Clean","Size":"85ml","Gender":"Unisex","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LACOSTE WHITE.png"},
  {"Id":72,"Name":"L-White 12.12Unisex","Brand":"Lacoste","Category":"Fresh/Clean","Size":"85ml, ","Gender":"Unisex","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LACOSTE WHITE.png"},
  {"Id":73,"Name":"WoodSage&SeaSalt","Brand":"Jo Malone","Category":"Woody/Salty","Size":"85ml, ","Gender":"Unisex","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/WOODSAGE.png"},
  {"Id":74,"Name":"L. White 12.12 Unisex","Brand":"Lacoste","Category":"Fresh/Citrus","Size":"85ml / ","Gender":"Unisex","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LACOSTE WHITE.png"},
  {"Id":75,"Name":"J.M WoodSage&SeaSalt","Brand":"Jo Malone","Category":"Woody/Fresh","Size":"85ml","Gender":"Unisex","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/WOODSAGE.png"},
  {"Id":76,"Name":"Seductive Man","Brand":"Guess","Category":"Spicy/Woody","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SEDUCTIVE MAN GUESS.png"},
  {"Id":77,"Name":"Happy Clinique","Brand":"Clinique","Category":"Citrus/Fresh","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/HAPPY.png"},
  {"Id":78,"Name":"Light Blue Men","Brand":"D&G","Category":"Citrus/Fresh","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LIGHT BLUE MEN.png"},
  {"Id":79,"Name":"Fahrenheit","Brand":"Dior","Category":"Woody/Spicy","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/FAHRENHEIT.png"},
  {"Id":80,"Name":"Cool Water Men","Brand":"Davidoff","Category":"Fresh/Aquatic","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/COOL WATER MEN.png"},
  {"Id":81,"Name":"Swiss Army","Brand":"Swiss Army","Category":"Fresh/Aromatic","Size":"85ml","Gender":"Men","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/SWISS AMRY.png"},
  {"Id":82,"Name":"White Musk","Brand":"The Body Shop","Category":"Musk/Clean","Size":"85ml","Gender":"Unisex","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/WHITE MUSK.png"},
  {"Id":83,"Name":"Red Lacoste","Brand":"Lacoste","Category":"Floral/Fruity","Size":"85ml","Gender":"Women","SellingPrice":220,"ImagePath":"images/PERFUME BOTTLES/LACOSTE RED.png"}
];

// Explicitly set on window object for global access
window.perfumesData = perfumesData;
console.log('✅ Perfumes data loaded:', perfumesData.length, 'items');
